version: '3' # Версія Docker Compose файлу

services: # Визначення сервісів

  web: # Налаштування веб-сервера
    image: nginx:latest # Використання останнього образу Nginx
    ports: # Перенаправлення портів
      - "80:80" # Перенаправлення порту 80 контейнера на порт 80 хоста
    volumes: # Монтування томів (файлів/каталогів)
      - ./path/to/your/website:/usr/share/nginx/html # Монтування каталогу з веб-сторінками в контейнер
    depends_on: # Залежності сервісу
      - server # Залежність від іншого сервісу з назвою "server"
    restart: always # Перезапуск сервісу завжди при його зупинці або завершенні

  server: # Налаштування сервера
    build: ./path/to/your/server # Збірка образу з Dockerfile за вказаним шляхом
    ports: # Перенаправлення портів
      - "3000:3000" # Перенаправлення порту 3000 контейнера на порт 3000 хоста
    volumes: # Монтування томів (файлів/каталогів)
      - ./path/to/your/server:/app # Монтування каталогу з серверним кодом в контейнер
    environment: # Змінні середовища
      - NODE_ENV=production # Встановлення значення змінної середовища NODE_ENV в "production"
    restart: always # Перезапуск сервісу завжди при його зупинці або завершенні

